spring:
  jpa:
    hibernate:
      ddl-auto: create
      format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
    maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/postgres
    username: "jaehuek"
    password: "1234"
    driver-class-name: org.postgresql.Driver
